#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
require(__DIR__ . '/vendor/autoload.php');

// Setup application environment
$envs = ['development', 'staging', 'production', 'local', 'test', 'automatedtests'];
$env = getenv("APPLICATION_ENV");

if (!in_array($env, $envs)) {
    echo("Environment is not valid");
    exit(1);
}

if (in_array($env, ['local', 'develop'])) {
    defined('YII_DEBUG') or define('YII_DEBUG', true);
}

require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . "/config/console.php");

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);